# Generated by Django 4.2.3 on 2023-07-03 10:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RentaRregistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("deleted", models.BooleanField(blank=True, default=False, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                (
                    "customer_booking_number",
                    models.CharField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("customer_first_name", models.CharField(max_length=254, null=True)),
                (
                    "customer_last_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "pickup_pre_book_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "datetime_of_pickup",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "datetime_of_return",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("kilometer_run", models.FloatField(blank=True, default=0, null=True)),
                ("rental_price", models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                "db_table": "renta_registration",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("deleted", models.BooleanField(blank=True, default=False, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_on", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "vehicle_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=16, null=True, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compact", "Compact"),
                            ("premium", "Premium"),
                            ("minivan", "Minivan"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("current_mileage", models.CharField(default=0, max_length=254)),
                ("booked_status", models.BooleanField(default=False)),
                (
                    "current_rent_registration",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carrental.rentarregistration",
                    ),
                ),
            ],
            options={
                "db_table": "cars",
            },
        ),
    ]
