# Generated by Django 4.2.3 on 2023-07-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrental", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="current_mileage",
        ),
        migrations.RemoveField(
            model_name="rentarregistration",
            name="customer_booking_number",
        ),
        migrations.AddField(
            model_name="rentarregistration",
            name="current_mileage_pickup",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="rentarregistration",
            name="current_mileage_return",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
